# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _pyradar
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


volume_exists = _pyradar.volume_exists
get_radar = _pyradar.get_radar
get_nvolumes = _pyradar.get_nvolumes
free_radar = _pyradar.free_radar
get_radar_header = _pyradar.get_radar_header
get_volume = _pyradar.get_volume
get_nsweeps = _pyradar.get_nsweeps
get_lat = _pyradar.get_lat
get_lon = _pyradar.get_lon
get_sweep = _pyradar.get_sweep
get_ray = _pyradar.get_ray
get_value = _pyradar.get_value
get_value_debug = _pyradar.get_value_debug
get_storage = _pyradar.get_storage
get_ngates = _pyradar.get_ngates
get_first_gate = _pyradar.get_first_gate
get_gate_size = _pyradar.get_gate_size
get_nrays = _pyradar.get_nrays
get_azimuth = _pyradar.get_azimuth
get_elev = _pyradar.get_elev
get_yr = _pyradar.get_yr
get_month = _pyradar.get_month
get_day = _pyradar.get_day
get_hour = _pyradar.get_hour
get_min = _pyradar.get_min
get_sec = _pyradar.get_sec
get_radarname = _pyradar.get_radarname


